predictor:
  model_path: /Users/fajar/Code/PyFrameParser/model/model.tar.gz
  model_type: LOME
  gpu: -1

credentials:
  credentials_path: /Users/fajar/Code/PyFrameParser/server/creds.csv
  ttl: 10

api:
  ttl: 10
